//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public decimal PetID { get; set; }
        public string PetName { get; set; }
        public string PetDescription { get; set; }
        public System.DateTime create_dt { get; set; }
        public string AnimalTypeCD { get; set; }
    
        public virtual AnimalType AnimalType { get; set; }
    }
}
